### ISSUE TITLE
Feature: Ad some UTC Time, in addtion to the Blocktime

### ISSUE THREAD

**Issue by martinkrung** [DiligentDeer/Sturdy-Aggregator-Analytics#1]
Nice stuff! 

I think it would be nice to show some UTC Time, not only Blocktime. Not in the chart,  I think in the overview this may be enough. 

Somewhere here:

![Screenshot at 2024-03-27 12-59-43](https://github.com/DiligentDeer/Sturdy-Aggregator-Analytics/assets/918180/2a835f7a-87d0-4499-a8ff-9ebc5f6b56b4)

Like this I don't know how fresh the data is.

**Comment by DiligentDeer** [comment]
Failed to respond to this issue earlier

Thank you for reaching out @martinkrung 

We did consider your suggestion and added that feature with this [commit](https://github.com/DiligentDeer/Sturdy-Aggregator-Analytics/commit/c362fa95aafe0ad68ca8cbcbae6981d54e654606).

**Comment by martinkrung** [comment]
thanks sir!
